### ISSUE TITLE
README update?

### ISSUE THREAD

**Issue by jmarceli** [stevearc/pypicloud-docker#18]
Hi,

Here is my example `docker-compose.yml` file (if anyone needs that):
```
version: '2'

services:
  pypi:
    image: stevearc/pypicloud:1.0.5-py3-baseimage
    container_name: pypi
    volumes:
      - ./config/config.ini:/etc/pypicloud/config.ini:ro
      - ./packages:/etc/pypicloud/packages:rw
```

What is more `config.ini` generated with `docker run -it --rm -v $(pwd):/out stevearc/pypicloud make-config -r /out/config.ini` doesn't work out of the box so I have to copy content of `/etc/pypicloud/config.ini` after running the container with default config file.
I may have done something wrong but it seems to be the only way in my case.
Interpolation by `pserve` (described in https://github.com/stevearc/pypicloud-docker/issues/5) probably doesn't work well because it generates a lot of permissions related errors.

Anyway thanks for the container. It seems to be working as expected :)

**Comment by stevearc** [comment]
Thanks for filing, yeah it looks like the config generation hadn't been updated. Should be fixed in https://github.com/stevearc/pypicloud/commit/9dfa4e3a059266191b1a216f8ffaaa5477501ded

Noticed a bunch of other small issues with the docker container while I was at it, will fix those shortly.

Also if you're looking to use docker compose, you can check out https://github.com/stevearc/pypicloud-docker/tree/master/compose for more examples of how to use it with different backend services (mysql, redis, etc)

**Comment by jmarceli** [comment]
Hi, thanks for the reply. Finally, I ended up with:
```
version: '2'

services:
  pypi:
    image: stevearc/pypicloud:1.0.5
    container_name: pypi
    ports:
      - "80:8080"
      #- "443:8443"
    volumes:
      - ./pypicloud/packages:/var/lib/pypicloud/packages:rw
      - ./pypicloud/db:/var/lib/pypicloud/db:rw
      - ./config/config.ini:/etc/pypicloud/config.ini:ro
```
FYI: When I enable shared sqlite db directory I have to set uWSGI as root because in other case there is a problem with file permissions to write DB files.

Still, I have an unsolved issue of running pypicloud with SSL support. Maybe you could write some example docker-compose/config file or just give some hint how to do this. I've tried probably all possible configurations described in http://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html and none of them works for me. Here is what I ended up with:
```
[uwsgi]
shared-socket = 0.0.0.0:8443
https = =0,cert=mykey.crt,key=mykey.key
http-to = /tmp/uwsgi.sock
```
The container output:
```
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uwsgi shared socket 0 bound to TCP address :8443 fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8080 fd 4
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x1133830
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your mercy for graceful operations on workers is 15 seconds
*** Operational MODE: no-workers ***
Loading paste environment: config:/etc/pypicloud/config.ini
/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x1133830 pid: 14 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
spawned uWSGI master process (pid: 14)
spawned uWSGI http 1 (pid: 18)
```
